namespace: eksa-packages
sourceRegistry: "public.ecr.aws/aws-containers"
repository: "aws-containers/hello-eks-anywhere"
tag: "{{aws-containers/hello-eks-anywhere}}"
title: "Amazon EKS Anywhere"
subtitle: "Run EKS in your datacenter"
